baseURL: "https://larry.motalavigne.com/"
title: "Larry Mota--Lavigne"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

defaultContentLanguage: fr

minify:
  disableXML: true

languages:
  fr:
    languageName: ":fr:"
    params:
      languageAltTitle: French
      weight: 1
      menu:
        main:
          - identifier: posts
            name: Articles
            url: /posts/
            weight: 10
          - identifier: projects
            name: Projets
            url: /projects/
            weight: 20
      profileMode:
        enabled: true
        title: "Larry Mota--Lavigne"
        subtitle: "Senior Python Developer 🐍 💻️"
        imageUrl: "/larry.jpg"
        imageWidth: 240
        imageHeight: 240
        imageTitle: "my picture"
        buttons:
          - name: "📃 Articles"
            url: /posts
          - name: "💡 Projets"
            url: /projects

outputs:
  home:
    - HTML
    - RSS

params:
  env: production # to enable google analytics, opengraph, twitter-cards, and schema.
  title: "Larry Mota--Lavigne"
  description: "Larry Mota--Lavigne's blog and website"
  keywords: [Blog, Portfolio, Dev life]
  author: Larry
  images: ["larry.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  displayFullLangName: true

  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "favicon/favicon.ico"
    favicon16x16: "favicon/favicon-16x16.png"
    favicon32x32: "favicon/favicon-32x32.png"
    apple_touch_icon: "favicon/apple-touch-icon.png"

  label:
    text: "⌂"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/LarryMotaL"
    - name: linkedin
      url: "https://linkedin.com/in/larrymotalavigne"
    - name: github
      url: "https://github.com/LarryMotaLavigne"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  editPost:
    URL: "https://github.com/larryMotaLavigne/blog/tree/master/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

disqusShortname: larrymotalavigne